import * as Page from "./pages";

export const routes = {
  "/": {
    name: "Home",
    exact: true,
    protected: false,
    withHeader: true,
    withFooter: true,
    element: <Page.HomePage />,
  },
  "/resume": {
    name: "Résumé",
    exact: true,
    protected: false,
    withHeader: true,
    withFooter: true,
    navOrder: 1,
    element: <Page.ResumePage />,
  },
  "/projects": {
    name: "Projects",
    exact: true,
    protected: true,
    withHeader: true,
    withFooter: true,
    navOrder: 2,
    element: <Page.ProjectsPage />,
  },
  "/project/:projectName": {
    name: "Project",
    exact: false,
    protected: true,
    withHeader: true,
    withFooter: true,
    element: <Page.ProjectPage />,
  },
  // "/sandbox": {
  //   name: "Sandbox",
  //   exact: true,
  //   protected: true,
  //   withHeader: true,
  //   withFooter: true,
  //   navOrder: 3,
  //   element: <Page.SandboxPage />,
  // },
  "/login": {
    name: "Log In",
    exact: true,
    protected: false,
    withHeader: true,
    withFooter: true,
    darkenedBackground: true,
    element: <Page.LoginPage />,
  },
  "/logout": {
    name: "Log Out",
    exact: true,
    protected: false,
    withHeader: false,
    withFooter: true,
    element: <Page.LogoutPage />,
  },
  "/privacy-policy": {
    name: "Privacy Policy",
    exact: true,
    protected: false,
    withHeader: true,
    withFooter: true,
    element: <Page.PrivacyPolicyPage />,
  },
  "/terms-of-use": {
    name: "Terms of Use",
    exact: true,
    protected: false,
    withHeader: true,
    withFooter: true,
    element: <Page.TermsOfUsePage />,
  },
  "/404": {
    name: "Error 404",
    exact: true,
    protected: false,
    withHeader: false,
    withFooter: true,
    element: <Page.Error404Page />,
  },
  "*": {
    name: "Catch All",
    exact: false,
    protected: false,
    withHeader: false,
    withFooter: true,
    element: <Page.Error404Page />,
  },
};
